---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r, setup, echo = FALSE, message = FALSE}

library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

```


```{r, data, include = FALSE}

data("instacart")

instacart %>%
  janitor::clean_names()

```

# Graph 1

```{r, line_plot, echo = FALSE, message = FALSE, warning = FALSE}

instacart %>%
  sample_n(5000) %>%
  filter(department == "snacks") %>%
  group_by(order_dow) %>%
  count(aisle) %>%
  mutate(order_dow = factor(order_dow),
         order_dow = recode(order_dow,
                            "0" = "Sunday",
                            "1" = "Monday",
                            "2" = "Tuesday",
                            "3" = "Wednesday",
                            "4" = "Thursday",
                            "5" = "Friday",
                            "6" = "Saturday")) %>%
  ungroup() %>%
  plot_ly(type = 'scatter', mode = 'lines+markers') %>% 
  add_trace(x = ~order_dow, y = ~n, color = ~aisle) %>%
  layout(xaxis = list(title = "Day of the Week"),
         yaxis = list(title = "Order Frequency (n)"))

```

Column {data-width=650}
-----------------------------------------------------------------------

# Graph 2

```{r, plotly_boxplot, echo = FALSE, message = FALSE}

instacart %>% 
  filter(department == "snacks") %>% 
  plot_ly(type = "box",
          y = ~order_hour_of_day, color = ~aisle,
          colors = "viridis") %>%
  layout(xaxis = list(title = "Snack type"),
         yaxis = list(title = "Order hour of the day"))

```

Column {data-width=350}
-----------------------------------------------------------------------
# Graph 3

```{r, bar_plot, echo = FALSE, message = FALSE}

instacart %>%
  filter(department == "snacks") %>%
  count(aisle) %>%
  arrange(desc(n)) %>%
  mutate(
    aisle = factor(aisle),
    aisle = fct_reorder(aisle,n)) %>%
  plot_ly(type = "bar",
          x = ~aisle, y = ~n, 
          color = ~aisle, colors = "viridis") %>%
  layout(xaxis = list(title = "Snack type"),
         yaxis = list(title = "Order Frequency (n)"))

```

